sample:
	cp testcases/sample.txt input.txt
	python3 main.py
5:
	cp testcases/5.txt input.txt
	python3 main.py
10:
	cp testcases/10.txt input.txt
	python3 main.py

20:
	cp testcases/20.txt input.txt
	python3 main.py

30:
	cp testcases/30.txt input.txt
	python3 main.py
